### ISSUE TITLE
import-from-folder - import error

### ISSUE THREAD

**Issue by Macerio** [blackary/sis-tricks#4]
Hey Blackary, 
I'm trying to use that tricks but it seams that the .py cannot find utils folder when it runs : 
> ModuleNotFoundError: No module named 'utils'
Do you have any ideas of something i'm missing ? 

I'm on the last version of streamlit in SiS.

<img width="1508" alt="Screenshot 2023-03-10 at 10 34 44" src="https://user-images.githubusercontent.com/23484747/224279652-084588f9-822c-43b1-ac6f-6e71788860d2.png">
<img width="881" alt="Screenshot 2023-03-10 at 10 57 33" src="https://user-images.githubusercontent.com/23484747/224285786-1cdc892c-005e-4d6a-82aa-ea99507a3eec.png">

**Comment by blackary** [comment]
The first thing I would check would be to make sure your zip contains the folder `utils`, and not just the raw files in it. Locally, you can do this by unzipping the .zip, and seeing what comes out.

On SiS, you can do this 
```python
import zipfile
util_zip = zipfile.ZipFile('utils.zip')
st.write(util_zip.namelist())
```

**Comment by Macerio** [comment]
Yes, thanks for your help, indeed, instead of doing 
`zip -r utils.zip ./utils/*py`
probably better to do `zip -r utils.zip ./utils` to keep the same structure than in local mode. 

Thanks for your help :)
